### get all ksiegarnie
GET http://localhost:8080/webapi/ksiegarnie

### get all ksiegarnie with params
GET http://localhost:8080/webapi/ksiegarnie?phrase=abc
custom-header: custom-value
Cookie: some-cookie=some-value

### get ksiegarnie by id
GET http://localhost:8080/webapi/ksiegarnie/1
Accept: application/xml

### get ksiegarnie posiadajace ksiazke
GET http://localhost:8080/webapi/ksiazki/1/ksiegarnie
Accept: application/json

### create new ksiegarnia
POST http://localhost:8080/webapi/ksiegarnie
Content-Type: application/json

{
  "name": "Ksiegarnia Słońce",
  "logo": "https://img.redro.pl/obrazy/symbol-slonce-na-bialym-tle-700-132008340.jpg"
}